= CARLO MAGNO

== 1.L'idea di europa
L'idea di Europa si forma con Carlo Magno. Prima l'impero romano aveva come centro il mediterraneo e 
considerava il nord africa, l'asia minore come facente parte dello stesso impero. Con l'invasione degli 
arabi e l'avvento di Carlo Magno l'europa prende la forma che conosciamo noi adesso. 
Inoltre tutte le istituzioni europee adesso si trovano negli stessi posti che aveva carlo Magno come
centri di potere. 

== 2.Nascita di Carlo e Pipino il breve
Carlo Magno era figlio di Pipino il Breve e di lui non si sa esattamente quando naque. Tadizionalmente 
si fissa la data al 2 Aprile 742, ma di fatto all'epoca non si dava importanza a quando si nasceva. 
Analogamente il luogo di nascita è ignoto, ma probabilmente potrebbe essere in belgio. 

Alla nascita di Carlo, Pipino il breve non era Re ma era il maggiorgomo di palazzo, che di fatto teneva il potere.
I franchi erano l'unico popolo barbaro che aderiva completamente al cattolicesimo, e non ad altre forme
come l'arianesimo degli altri popoli barbari. Per questo il papa era molto favorevole nei confronti dei
franchi. 

Pipino voleva non solo comandare ma anche avere il titolo di re, pertanto, si accordò con il papa, 
e grazie ad un intenso scambio di lettere, tra cui in un cui si diceva:
'è guisot che chi comanda non è re, e che chi è re non comanda?' e a cui il papa aveva risposto 'no' 
si fece incoronare Re dal papa che era venuto in gallia proprio per questo. (ai tempi i viaggi del 
papa erano un evento rarissimo)

== 3.L'ascesa al trono 
Alla morte di Pipino il regno passa ai due figli Carlo e Carlomanno, non essendoci una regola che stabilische che 
il regno vada al primogentio. All'inzio le tensioni tra i due fratelli sono molte, tuttavia in questo periodo la 
madre Berta gestisce il potere, poi Carlomanno muore di malattia e Carlo diventa l'unico re.

Dato che la Moglie e i figli di Carlomanno scappano nel regno Longobardo ed un giorno avrebbero potuto 
rivendicare il regno, unito al fattoche Carlo sposa la figlia del re Longobardo _Desiderio_ (che il Manzoni
 chiama Ermenengarda, ma in realtà nessuno sa come si chiami) e dopo 
un anno la ripudia, unito al fatto che i Franchi erano difensori del Papa mentre i Longobardi avevano
più volte tentato di invadere il suo terrotorio, Carlo decide di invadere il territorio longobardo

== 4.La guerra contro i Longobardi
Il regno longobardo era difeso dai valichi alpini dalle 'chiuse' ( fortificazioni ) ed era possibile arrivare in 
Italia da due perorsi, tramite Moncenisio o tramite la val d'Aosta. Carlo decide di radunare il suo esercito a Ginevra
rendendo possibile l'utilizzo di entrambi i percorsi, e quindi non permettendo ai Longobardi di capire da che parte
sarebbe sceso. Inoltre divide il suo esercito in due parti : la maggiore comandata da lui e la fa scendere
dal Moncenisio, l'altra, più piccola, invece la fa comandare da suo zio e la fa scendere per un percorso alternativo.
Inoltre arrivati vicino al campo di Battaglia di Susa, riesce a trovare una strada alternativa, e prende l'esercito
Longobardo alle spalle. 

La battaglia è vinta senza nemmeno combattere. 

== 5.La caduta del regno Longobardo e il regno d'Italia
Dopo la sconfitta della Battaglia di Susa, il re longobardo Desiderio si rifugia a Pavia e rimane sotto assedio
per circa 1 anno; quando Carlo Magno riesce ad espugnare la città e a far rinchiudere Desidero in un monastero.
Adelchi invece a differenza di quanto narrato dal Manzoni, si rifugia a Costantinopoli. 

Carlo non annette il regno longobardo al regno franco ma si fa incoronare come re dei longobardi, mantenendo 
la struttura amministrativa longobarda (quel poco che c'era), inoltre piano piano il regno longobardo inizia
a chiamarsi Regno d'Italia. 

A seguito dell'invasione franca la misera era dilagante e in moltissimi 
avevano deciso di vendere tutto quello che avevano (compreso
se stessi o i famigliari come schiavi) decise di mettere un editto che rendeva nulle tutte le compravendite
avvenute dopo l'invasione, indicando come Carlo fosse anche un politico oltre che un conquistatore. 

== 6.Aspetto fisico e vita quotidiana di Carlo Magno
Carlo era abbastanza alto 1,9 ma non era un'eccezione per la media germanica dell'epoca, vestiva all maniera
dei franchi con una tunica allacciata in vita e portava i baffi come tutti i sui sudditi. 

La vita quotidiana a differenza di adesso che è scandita dai pasti era scandita dalle funzioni religiose. Il pasto era
unico e si faceva nel primo pomeriggio. 

== 7.Il carattere di Carlo Magno
Carlo era un gran mangione, (come doveva esserlo un re a quel tempo), gli piaceva andare a caccia e mangiare 
una gran quantità di cacciagione. Aveva un carattere sanguigno, che sapeva stare allo scherzo, ma per certe
cose andava in collera facilmente (specie durante le battaglie e le guerre) . 
Piaceva essere adulato, anche in maniera grossolana, ed inoltre aveva un interesse per l'attività intetlluali, 
scriveva anche qualche poesia. 

== 8.Guerra contro i Sassoni
I Franchi combatterono una lunghissima guerra di circa 30 anni contro i Sassoni. Per Carlo era importante sottomettere questo popolo pagano alle porte del regno franco. 
Grazie alla loro superiorità i franchi occupavano ogni anno il territorio dei sassoni con l'esecito, installavano avamposti e chiese e d'inverno l'esercito rientrava in patria. I sassoni una volta andato via l'esercito, distruggevano gli avanposti e uccidevano i prelati. In primavera l'esercito franco ritornava in territorio Sassone a ristabilire l'ordine. 

Questa situazione è andata avanti fino a che un anno Carlo ha deciso di fermarsi con l'esercito in territorio Sassone anche d'inverno e di bloccare la possibilità ai Sassoni di riprendersi. 

La guerra contro i Sassoni ha avuto dei momenti molto crudeli, ad esempio una volta Carlo ha deciso di uccidere in un sol giorno 4000 ostaggi sassoni, oppure ha effettuato delle deporazioni di massa. 

Inoltre si cercava di convertire a forza al cristianesimo le popolazioni sassoni. C'era la pena di morte se qualcuno veniva sorpreso a fare i riti pagani o non rispettava la quaresima. Questo atteggiamento coercitivo ha causato un acceso dibattito all'interno dei franchi se sia giusto o meno obbligare qualcuno a crede in una fede. 
Difatti nella sucessiva guerra contro gli Avari (altro popolo pagano) si è deciso non costringere con la forza a credere nel cristianesimo

La guerra contro i Sassoni è stata molto dura e ha visto 

== 9.Carlo le donne e i Matrimoni
Carlo ebbe 5 mogli ufficiali, numerose concubine e più di 18 figli. Nel'arco della vita di carlomagno il concetto di matrimonio si è evoluto, specialmente in quanto la chiesa ha iniziato ad interessarsi a questo aspetto. Infatti quando Carlo era giovane, il matrimonio germanico 'per amore' e il matrimonio ufficiale (quello in cui due famiglie si accordavano sui beni da scambiarsi) erano parificati e il matriomonio non era considerato un sacramento. Carlo infatti era nato da un matrimonio 'per amore' ed era parificato a Carlomanno che era nato dopo che suo padre Pipino e sua Madre Berta si sono sposati anche ufficialmente. 

Sucessivamente la chiesa ha inizato ad affermare che il matrimonio 'ufficiale' aveva più importanza rispetto a quello per 'amore' e che ci si doveva sposare una sola volta. 

Al tempo si avevano moltissime mogli perché morivano spesso per parto, ad esempio Ildegarda sua terza moglie gli diede 9 figli e quando morì aveva 25 anni. 


== 10.I figli

== 11.Carlo e l'Islam
Al tempo di Carlo l'islam era moderato e più avanzato delle popolazioni europee. Era permessa la libertà di culto, addirittura, c'erano dei vescovi cristiani spagnoli che pur vivendo sotto l'Islam avevano il permesso di recarsi ai concilii senza problemi. 
La spagna era completamente sotto il dominio arabo, (a suo tempo aveva anche cercato di passare oltre i pireneii ma carlo martello li aveva fermati a Poitiers) e aveva cercato, senza successo entrare in Spagna. 
L'unico territorio che riuscì a conquistare fu la catalogna, che forse anche per questo si sente un po' più europeea del resto della spagna. 
Quando Carlo si ritirò la retrovia dell'esercito venne attaccato e fu una grande perdita. Da questo evento sono nate le gesta di Rolando. La cosa che non è nota è che l'attacco non è avvenuto per causa dell'islamici di spagna ma a causa delle popolazione basche. 

I rapporti con il califfo di Bagdad erano più che buoni. I due sovrani non avevano terreni confinanti (La spagna era ribelle rispetto al califfato) ed avevano tutti e due probemi con l'impero bizantino. Inolte c'era un intenso scambio di doni, tuttavia data la superiorità del califfo rispetto a carlo i doni destavano sempre stupore nei franchi. 
Una volta addirittura il califfo regalò a Carlo un Elefante, cosa che destò stupore assoluto. Tuttavia nei documenti dei califfo l'elefante veniva considerato un regalo per i sovrani di second'ordine. Carlo non lo seppe mai. 
