= CARLO MAGNO

== 1.L'idea di europa
L'idea di Europa si forma con Carlo Magno. Prima l'impero romano aveva come centro il mediterraneo e 
considerava il nord africa, l'asia minore come facente parte dello stesso impero. Con l'invasione degli 
arabi e l'avvento di Carlo Magno l'europa prende la forma che conosciamo noi adesso. 
Inoltre tutte le istituzioni europee adesso si trovano negli stessi posti che aveva carlo Magno come
centri di potere. 

== 2.Nascita di Carlo e Pipino il breve
Carlo Magno era figlio di Pipino il Breve e di lui non si sa esattamente quando naque. Tadizionalmente 
si fissa la data al 2 Aprile 742, ma di fatto all'epoca non si dava importanza a quando si nasceva. 
Analogamente il luogo di nascita è ignoto, ma probabilmente potrebbe essere in belgio. 

Alla nascita di Carlo, Pipino il breve non era Re ma era il maggiorgomo di palazzo, che di fatto teneva il potere.
I franchi erano l'unico popolo barbaro che aderiva completamente al cattolicesimo, e non ad altre forme
come l'arianesimo degli altri popoli barbari. Per questo il papa era molto favorevole nei confronti dei
franchi. 

Pipino voleva non solo comandare ma anche avere il titolo di re, pertanto, si accordò con il papa, 
e grazie ad un intenso scambio di lettere, tra cui in un cui si diceva:
'è guisot che chi comanda non è re, e che chi è re non comanda?' e a cui il papa aveva risposto 'no' 
si fece incoronare Re dal papa che era venuto in gallia proprio per questo. (ai tempi i viaggi del 
papa erano un evento rarissimo)

== 3.L'ascesa al trono 
Alla morte di Pipino il regno passa ai due figli Carlo e Carlomanno, non essendoci una regola che stabilische che 
il regno vada al primogentio. All'inzio le tensioni tra i due fratelli sono molte, tuttavia in questo periodo la 
madre Berta gestisce il potere, poi Carlomanno muore di malattia e Carlo diventa l'unico re.

Dato che la Moglie e i figli di Carlomanno scappano nel regno Longobardo ed un giorno avrebbero potuto 
rivendicare il regno, unito al fattoche Carlo sposa la figlia del re Longobardo _Desiderio_ (che il Manzoni
 chiama Ermenengarda, ma in realtà nessuno sa come si chiami) e dopo 
un anno la ripudia, unito al fatto che i Franchi erano difensori del Papa mentre i Longobardi avevano
più volte tentato di invadere il suo terrotorio, Carlo decide di invadere il territorio longobardo

== 4.La guerra contro i Longobardi
Il regno longobardo era difeso dai valichi alpini dalle 'chiuse' ( fortificazioni ) ed era possibile arrivare in 
Italia da due perorsi, tramite Moncenisio o tramite la val d'Aosta. Carlo decide di radunare il suo esercito a Ginevra
rendendo possibile l'utilizzo di entrambi i percorsi, e quindi non permettendo ai Longobardi di capire da che parte
sarebbe sceso. Inoltre divide il suo esercito in due parti : la maggiore comandata da lui e la fa scendere
dal Moncenisio, l'altra, più piccola, invece la fa comandare da suo zio e la fa scendere per un percorso alternativo.
Inoltre arrivati vicino al campo di Battaglia di Susa, riesce a trovare una strada alternativa, e prende l'esercito
Longobardo alle spalle. 

La battaglia è vinta senza nemmeno combattere. 

== 5.La caduta del regno Longobardo e il regno d'Italia
Dopo la sconfitta della Battaglia di Susa, il re longobardo Desiderio si rifugia a Pavia e rimane sotto assedio
per circa 1 anno; quando Carlo Magno riesce ad espugnare la città 

== 6.Aspetto fisico e vita quotidiana di Carlo Magno
