= CARLO MAGNO

== 1.L'idea di europa
L'idea di Europa si forma con Carlo Magno. Prima l'impero romano aveva come centro il mediterraneo e 
considerava il nord africa, l'asia minore come facente parte dello stesso impero. Con l'invasione degli 
arabi e l'avvento di Carlo Magno l'europa prende la forma che conosciamo noi adesso. 
Inoltre tutte le istituzioni europee adesso si trovano negli stessi posti che aveva carlo Magno come
centri di potere. 

== 2.Nascita di Carlo e Pipino il breve
Carlo Magno era figlio di Pipino il Breve e di lui non si sa esattamente quando naque. Tadizionalmente 
si fissa la data al 2 Aprile 742, ma di fatto all'epoca non si dava importanza a quando si nasceva. 
Analogamente il luogo di nascita è ignoto, ma probabilmente potrebbe essere in belgio. 

Alla nascita di Carlo, Pipino il breve non era Re ma era il maggiorgomo di palazzo, che di fatto teneva il potere.
I franchi erano l'unico popolo barbaro che aderiva completamente al cattolicesimo, e non ad altre forme
come l'arianesimo degli altri popoli barbari. Per questo il papa era molto favorevole nei confronti dei
franchi. 

Pipino voleva non solo comandare ma anche avere il titolo di re, pertanto, si accordò con il papa, 
e grazie ad un intenso scambio di lettere, tra cui in un cui si diceva:
'è guisot che chi comanda non è re, e che chi è re non comanda?' e a cui il papa aveva risposto 'no' 
si fece incoronare Re dal papa che era venuto in gallia proprio per questo. (ai tempi i viaggi del 
papa erano un evento rarissimo)

== 3.L'ascesa al trono 
Alla morte di Pipino il regno passa ai due figli Carlo e Carlomanno, non essendoci una regola che stabilische che 
il regno vada al primogentio. All'inzio le tensioni tra i due fratelli sono molte, tuttavia in questo periodo la 
madre Berta gestisce il potere, poi Carlomanno muore di malattia e Carlo diventa l'unico re.

Dato che la Moglie e i figli di Carlomanno scappano nel regno Longobardo ed un giorno avrebbero potuto 
rivendicare il regno, unito al fattoche Carlo sposa la figlia del re Longobardo _Desiderio_ (che il Manzoni
 chiama Ermenengarda, ma in realtà nessuno sa come si chiami) e dopo 
un anno la ripudia, unito al fatto che i Franchi erano difensori del Papa mentre i Longobardi avevano
più volte tentato di invadere il suo terrotorio, Carlo decide di invadere il territorio longobardo

== 4.La guerra contro i Longobardi
Il regno longobardo era difeso dai valichi alpini dalle 'chiuse' ( fortificazioni ) ed era possibile arrivare in 
Italia da due perorsi, tramite Moncenisio o tramite la val d'Aosta. Carlo decide di radunare il suo esercito a Ginevra
rendendo possibile l'utilizzo di entrambi i percorsi, e quindi non permettendo ai Longobardi di capire da che parte
sarebbe sceso. Inoltre divide il suo esercito in due parti : la maggiore comandata da lui e la fa scendere
dal Moncenisio, l'altra, più piccola, invece la fa comandare da suo zio e la fa scendere per un percorso alternativo.
Inoltre arrivati vicino al campo di Battaglia di Susa, riesce a trovare una strada alternativa, e prende l'esercito
Longobardo alle spalle. 

La battaglia è vinta senza nemmeno combattere. 

== 5.La caduta del regno Longobardo e il regno d'Italia
Dopo la sconfitta della Battaglia di Susa, il re longobardo Desiderio si rifugia a Pavia e rimane sotto assedio
per circa 1 anno; quando Carlo Magno riesce ad espugnare la città e a far rinchiudere Desidero in un monastero.
Adelchi invece a differenza di quanto narrato dal Manzoni, si rifugia a Costantinopoli. 

Carlo non annette il regno longobardo al regno franco ma si fa incoronare come re dei longobardi, mantenendo 
la struttura amministrativa longobarda (quel poco che c'era), inoltre piano piano il regno longobardo inizia
a chiamarsi Regno d'Italia. 

A seguito dell'invasione franca la misera era dilagante e in moltissimi 
avevano deciso di vendere tutto quello che avevano (compreso
se stessi o i famigliari come schiavi) decise di mettere un editto che rendeva nulle tutte le compravendite
avvenute dopo l'invasione, indicando come Carlo fosse anche un politico oltre che un conquistatore. 

== 6.Aspetto fisico e vita quotidiana di Carlo Magno
Carlo era abbastanza alto 1,9 ma non era un'eccezione per la media germanica dell'epoca, vestiva all maniera
dei franchi con una tunica allacciata in vita e portava i baffi come tutti i sui sudditi. 

La vita quotidiana a differenza di adesso che è scandita dai pasti era scandita dalle funzioni religiose. Il pasto era
unico e si faceva nel primo pomeriggio. 

== 7.Il carattere di Carlo Magno
Carlo era un gran mangione, (come doveva esserlo un re a quel tempo), gli piaceva andare a caccia e mangiare 
una gran quantità di cacciagione. Aveva un carattere sanguigno, che sapeva stare allo scherzo, ma per certe
cose andava in collera facilmente (specie durante le battaglie e le guerre) . 
Piaceva essere adulato, anche in maniera grossolana, ed inoltre aveva un interesse per l'attività intetlluali, 
scriveva anche qualche poesia. 

== 8.Guerra contro i Sassoni
I Franchi combatterono una lunghissima guerra di circa 30 anni contro i Sassoni. Per Carlo era 
Grazie alla loro superiorità
numerica i franchi occupavano ogni anno il territorio dei sassoni con l'esecito, installav
