= CARLO MAGNO

== Cap 1 - L'idea di europa
L'idea di Europa si forma con Carlo Magno. Prima l'impero romano aveva come centro il mediterraneo e 
considerava il nord africa, l'asia minore come facente parte dello stesso impero. Con l'invasione degli 
arabi e l'avvento di Carlo Magno l'europa prende la forma che conosciamo noi adesso. 
Inoltre tutte le istituzioni europee adesso si trovano negli stessi posti che aveva carlo Magno come
centri di potere. 

== Cap 2 - Nascita di Carlo e Pipino il breve
Carlo Magno era figlio di Pipino il Breve e di lui non si sa esattamente quando naque. Tadizionalmente 
si fissa la data al 2 Aprile 742, ma di fatto all'epoca non si dava importanza a quando si nasceva. 
Analogamente il luogo di nascita è ignoto, ma probabilmente potrebbe essere in belgio. 

Alla nascita di Carlo, Pipino il breve non era Re ma era il maggiorgomo di palazzo, che di fatto teneva il potere.
I franchi erano l'unico popolo barbaro che aderiva completamente al cattolicesimo, e non ad altre forme
come l'arianesimo degli altri popoli barbari. Per questo il papa era molto favorevole nei confronti dei
franchi. 

Pipino voleva non solo comandare ma anche avere il titolo di re, pertanto, si accordò con il papa, 
e grazie ad un intenso scambio di lettere, tra cui in un cui si diceva:
'è guisot che chi comanda non è re, e che chi è re non comanda?' e a cui il papa aveva risposto 'no' 
si fece incoronare Re dal papa che era venuto in gallia proprio per questo. (ai tempi i viaggi del 
papa erano un evento rarissimo)
