= NFS
:revdate: 12/2/2014

== SERVER

     aptitude install nfs-common, nfs-kernel-server
    
editare il file /etc/exports nel seguente modo:

    NomeDirDaEsportare host1(opt) host2(opt) 
es: 

    /home/test01/Software/Linux srv.domain.it(ro) 192.168.1.1(rw) 
    
    systemctl enable nfs-server
    
    exportfs 			mostra i filesystem esportati
    
== CLIENT

mostra gli export nfs di un host 192.168.1.100

     showmount -e 192.168.1.100

su arch : 

    sudo pacman -S nfs-utils
    
    (forse i seguenti non servono)
    sudo systemctl start rpcbind.service
    sudo systemctl start nfs-client.target



    mount nomehost:/directory/ /mount/point 	per montare una directory via nfs

es

    sudo mount 192.168.1.51:/mnt/HD/HD_a2 ./nas/

se c'è l'errore : *mount.nfs: Operation not permitted* bisogna forzare nfs3

     mount.nfs remote target directory -o ...,nfsvers=3,...

o in /etc/fstab:

     remote target directory nfs ...,nfsvers=3,... 0 0

su fstab
    
    # NAS (no auto)
    nfs_server:/mnt/HD/HD_a2 /mnt/nas nfs rw,hard,intr,nolock,noauto,user 0 0

    #NAS auto
    nfs_server:/mnt/HD/HD_a2 /mnt/nas nfs rw,hard,intr,nolock,user 0 0
 
== Permessi

devono essere messi sul server (non è possibile ad esempio modificare l'owner di una cartella da root del client)

