= Programmi Vari
:author: Giuliano Dedda 
:date: 17/07/2014

== corkscrew

    pacman -S corkscrew
   
Configue corkscrew

    touch .corkscrew-auth
    nano .corkscrew-auth
    username:password
    
Configure ssh For Tunneling

    vim /home/yourusername/.ssh/config
    Host *
    ProxyCommand corkscrew proxyhostname proxyport %h %p /home/username/.corkscrew-auth

Test your SSH connection

    ssh serverip


== Webdav

=== davfs2

installare davfs2 

==== Proxy
in /etc/davfs2/davfs2.conf inserire

    proxy 127.0.0.1:28080

==== montare le directory

in /etc/davfs2/secrets inserire:
    
    https://dav.box.com/dav nome_utente_box_com@email.info password_box_com

per montare un disco remoto con l'utente_a inserire in /etc/fstab

    https://dav.box.com/dav /home/utente_a/mnt/box.com    davfs   defaults,uid=utente_a,gid=gruppo_a,noauto  0       0
    
== OCR 

=== tesseract

installare anche community/tesseract-data-ita

tesseract converte solo da tif pertanto bisogna convertire i file prima:
su : http://wiki.ubuntu-it.org/Grafica/Ocr c'è una buona guida e un programma per converitire un PDF con più pagine.


== UPNP/DNLA

== ReadyMedia (ex minidnla)

    pacman -S minidlna
    nano /etc/minidlna.conf
    
modificare i seguenti campi:
    user=test-amm               # utente con cui parte il server
    media_dir=/mnt/Musica       # directory dove si trovano i media (è possibile inserirne più di uno)
    friendly_name=RasberryPi    # nome visualizzato del server DNLA

con un browser su http://ip.server:8200/ si vedono le statistiche

Per fare il rescan del db

    minidlnad -R

=== Rygel

    sudo pacman -S rygel
    sudo pacman -S gst-plugins-base gst-plugins-good gst-plugins-bad gst-plugins-ugly gst-libav

edit di /etc/rygel.conf ed impostare il title con il nome del server in 

[Tracker]
title=nome_del_server
e 
[MediaExport]
enabled=true
title=nome_del_server

inserire la cartella in cui ci sono le canzoni o i video separate da ;

fare il servizio per systemd 
nano /usr/lib/systemd/system/rygel@.service

```
[Unit]
Description=Rygel DLNA server
After=syslog.target

[Service]
ExecStart=/usr/bin/rygel
User=%i

[Install]
WantedBy=multi-user.target
```

e lanciarlo con 

   systemctl start rygel@<nome-utente>
   




